name: Test python package dpath-python
    # ------------------------------------------------------------
    # (C) Alain Lichnewsky, 2021
    #
    # For running under Github's Actions
    #
    # Script performs basic test of the Python-3 version of the package
    # including added functionality.
    # ------------------------------------------------------------

on: #[push]
    workflow_dispatch:

jobs:
    test-python3:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'
                  architecture: 'x64'

            - name: Ascertain configuration
              #
              #    Collect information concerning $HOME and the location of
              #    file(s) loaded from Github/
              run: |
                echo Working dir: $(pwd)
                echo Files at this location:
                ls -ltha
                echo HOME: ${HOME}
                echo LANG: ${LANG}  SHELL: ${SHELL}
                which python
                echo LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}
                echo PYTHONPATH: \'${PYTHONPATH}\'

                #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                #    ** here (it is expected that) **
                #  pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
                #  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
                #  Working dir /home/runner/work/dpath-python/dpath-python
                #  HOME: /home/runner
                #  LANG: C.UTF-8
                #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

            - name: Install dependencies

                #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                #  requirements install the test framework, which is not
                #  required by the package in setup.py
                #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              run: |
                python -m pip install --upgrade pip setuptools wheel
                if [ -f requirements.txt ]; then
                   pip install -r requirements.txt;
                fi
                python setup.py install
                echo which nose :$(which nose)
                echo which nose2: $(which nose2)
                echo which nose2-3.6: $(which nose2-3.6)
                echo which nose2-3.8: $(which nose2-3.8)

            - name: Test
              run: |
                nose2
