name: Test python package dpath-python with regexp extension
  # ------------------------------------------------------------
  # (C) Alain Lichnewsky, 2021, 2022, 2023
  #
  # For running under Github's Actions
  #
  # Script performs basic test of the Python-3 version of the package
  # including added functionality (regexp in search paths).
  # ------------------------------------------------------------
  
  # *****************************
  # ADDED FOR TESTING PRIOR TO PR
  # REMOVE FROM PR submission
  # *****************************

on:
    workflow_dispatch:
    # Allows manual dispatch from the Actions tab

jobs:
    test-python3:

        timeout-minutes: 60

        runs-on: ubuntu-latest

        strategy:
            matrix:
                # Match versions specified in tox.ini
                python-version: ['3.8', '3.9', '3.10','3.11', 'pypy3.7', 'pypy3.9']

        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@main
              with:
                  python-version: ${{ matrix.python-version }}
                  architecture: 'x64'

            - name: Ascertain configuration
              #
              #    Collect information concerning $HOME and the location of
              #    file(s) loaded from Github/
              run: |
                echo Working dir: $(pwd)
                echo Files at this location:
                ls -ltha
                echo HOME: ${HOME}
                echo LANG: ${LANG}  SHELL: ${SHELL}
                which python
                echo LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}
                echo PYTHONPATH: \'${PYTHONPATH}\'

              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              #    ** here (it is expected that) **
              #  pythonLocation: /opt/hostedtoolcache/Python/3.8.8/x64
              #  LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.8/x64/lib
              #  Working dir /home/runner/work/dpath-python/dpath-python
              #  HOME: /home/runner
              #  LANG: C.UTF-8
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

            - name: Install dependencies
              shell: bash
              if: always()
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              #  requirements install the test framework, which is not
              #  required by the package in setup.py
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              run: |
                python -m pip install --upgrade pip setuptools wheel \
                        nose2 hypothesis
                if [ -f requirements.txt ]; then
                   pip install -r requirements.txt;
                fi
                python setup.py install
                echo which nose :$(which nose)
                echo which nose2: $(which nose2)
                echo which nose2-3.6: $(which nose2-3.6)
                echo which nose2-3.8: $(which nose2-3.8)

            - name: Tox testing
              shell: bash
              if: always()
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              #  move to tox testing, otherwise will have to parametrize
              #  nose in more details; here tox.ini will apply
              #  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
              run: |
                pip install tox
                echo "Installed tox"
                tox
                echo "Ran tox"
